server:
    address: localhost
    port: 8080
    servlet:
      context-path: /
      encoding:
        charset: UTF-8

spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tiny_url?useUnicode=true&createDatabaseIfNoExist=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
        username: testuser
        password: password
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    sql:
        init:
            encoding: UTF-8

logging:
    level:
        org:
            hibernate:
                SQL = DEBUG
            type:
                descriptor.sql.BasicBinder = TRACE